id: IDAC2D06A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T18:42:18+00:00'
last_modified: '2022-06-07T12:06:49.903208+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12430
  title: མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་བསྡུས་དོན་རིན་པོ་ཆེའི་ཕྲེང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1EF2:
      image_group_id: I4244
      title: ''
      total_pages: 630
      order: 1
      base_file: 1EF2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
